/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utils.DBConnection;

/**
 *
 * @author Shazia
 */
public class deregisterVoter extends javax.swing.JFrame {

    /**
     * Creates new form deregisterVoter
     */
    public deregisterVoter() {
        initComponents();
          setSize(500,500);
        setTitle("Election Commision");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        deregister = new javax.swing.JButton();
        vid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deregister Voter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 100, 207, 22);

        deregister.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deregister.setText("Deregister");
        deregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deregisterActionPerformed(evt);
            }
        });
        getContentPane().add(deregister);
        deregister.setBounds(220, 300, 95, 25);

        vid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidActionPerformed(evt);
            }
        });
        getContentPane().add(vid);
        vid.setBounds(220, 200, 104, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Voter ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 200, 51, 17);

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(120, 300, 73, 25);

        errorMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(errorMessage);
        errorMessage.setBounds(220, 230, 210, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vidActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
          adminHome ad = new adminHome();
        ad.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void deregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deregisterActionPerformed
      int a;
        a = JOptionPane.showConfirmDialog(this, "Are you sure?");
    if(a==JOptionPane.YES_OPTION){  
//    this.setDefaultCloseOperation(voterRegister.EXIT_ON_CLOSE);
         
        try {
            DBConnection connect = new DBConnection();
            Connection conn = connect.createConnection();
            Statement stmt = conn.createStatement();
            int voterid = Integer.parseInt(vid.getText());
            String DOB=null;
            ResultSet rs = stmt.executeQuery("select * from voters where voterid like '"+voterid+"'");
            while(rs.next()){
                DOB = rs.getString("dob");
            }
            if(DOB==null){
                    errorMessage.setText("Wrong details. Check again");
                    vid.setText("");
             }else{
      
                  int num = Integer.parseInt(vid.getText());
                String sql =  "delete from `voters` where `voterid` like (?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1,num);

                int r = ps.executeUpdate();
                if(r>0){
                System.out.print("Successful");
                adminHome ad = new adminHome();
                ad.setVisible(true);
               }
                conn.close();  
                } 
            
            
        }catch(SQLException e){
                    System.out.print(e);
                  }
        
        
      
        
    }
    else{
        vid.setText("");
        errorMessage.setText("");
    }
    }//GEN-LAST:event_deregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deregisterVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deregisterVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deregisterVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deregisterVoter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deregisterVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton deregister;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField vid;
    // End of variables declaration//GEN-END:variables
}
