/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import utils.DBConnection;

/**
 *
 * @author Shazia
 */
public class deregisterCandidate extends javax.swing.JFrame {

    /**
     * Creates new form deregisterCandidate
     */
    public deregisterCandidate() {
        initComponents();
        setSize(500,500);
        setTitle("Election Commision");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Deregister Candidate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 100, 191, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Candidate ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 190, 79, 17);

        cid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        getContentPane().add(cid);
        cid.setBounds(240, 190, 82, 23);

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(240, 290, 75, 25);

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(140, 290, 73, 25);

        errorMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(errorMessage);
        errorMessage.setBounds(240, 230, 140, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        adminHome ad = new adminHome();
        ad.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        int a;
        a = JOptionPane.showConfirmDialog(this, "Are you sure?");
    if(a==JOptionPane.YES_OPTION){  
//    this.setDefaultCloseOperation(voterRegister.EXIT_ON_CLOSE);
         
        try {
            DBConnection connect = new DBConnection();
            Connection conn = connect.createConnection();
            Statement stmt = conn.createStatement();
            int canID = Integer.parseInt(cid.getText());
            String DOB=null;
            ResultSet rs = stmt.executeQuery("select * from candidates where cid like '"+canID+"'");
            while(rs.next()){
                DOB = rs.getString("dob");
            }
            if(DOB==null){
                    errorMessage.setText("Wrong details. Check again");
                    cid.setText("");
             }else{
      
                int num = Integer.parseInt(cid.getText());
                String sql =  "delete from `candidates` where `cid` like (?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1,num);

                int r = ps.executeUpdate();
                if(r>0){
                System.out.print("Successful");
                adminHome ad = new adminHome();
                ad.setVisible(true);
               }
                conn.close();  
                } 
            
            
        }catch(SQLException e){
                    System.out.print(e);
                  }
        
        
      
        
    }
    else{
        cid.setText("");
        errorMessage.setText("");
    }
                // TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deregisterCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deregisterCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deregisterCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deregisterCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deregisterCandidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cid;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
