/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import models.User;
import utils.DBConnection;

/**
 *
 * @author Shazia
 */
public class voterLogin extends javax.swing.JFrame {

    /**
     * Creates new form voterLogin
     */
    public voterLogin() {
        initComponents();
            setSize(500,500);
        setTitle("Election Commision");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        dobText = new javax.swing.JTextField();
        invalidText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voter Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 80, 166, 22);

        home.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(150, 330, 69, 25);

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(240, 330, 75, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/user.png"))); // NOI18N
        jLabel2.setText("Voter ID");
        jLabel2.setIconTextGap(6);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 170, 74, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/cal.jpg"))); // NOI18N
        jLabel3.setText("Date  of Birth");
        jLabel3.setIconTextGap(6);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(101, 220, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("yyyy-mm-dd");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 250, 95, 13);
        getContentPane().add(vid);
        vid.setBounds(240, 170, 55, 20);
        getContentPane().add(dobText);
        dobText.setBounds(240, 220, 55, 20);

        invalidText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(invalidText);
        invalidText.setBounds(240, 280, 177, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        frame1 f1 = new frame1();
        f1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        int voterid = Integer.parseInt(vid.getText());
        String dob= dobText.getText();
        
        try {
            DBConnection connect = new DBConnection();
            Connection conn = connect.createConnection();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("select * from voters where voterid like '"+voterid+"' and dob like '"+dob+"'");
            User user1 = new User();
            String Lname="";
            String DateOB=null;
            String Fname ="";
            
//            if(!rs.next()){
//                    invalidText.setText("Wrong details. Check again");}
//            }else{
              
                 while(rs.next()){
//                 System.out.print("exists");
                 int wno= rs.getInt("ward");
                 int voterId= rs.getInt("voterid");
                 Lname = rs.getString("lname");
                 Fname= rs.getString("fname");
                 DateOB = rs.getString("dob");
                 
                    user1.setFname(Fname);
                    user1.setDob(DateOB);
                    user1.setLname(Lname);
                    user1.setVoterid(voterId);
                    user1.setWardno(wno);
                    
                    
                }
//                System.out.print(Lname);
//                System.out.print(user1.getFname());
//                System.out.print(user1.getLname());
//                System.out.print(user1.getDob());
                if(DateOB==null){
                    invalidText.setText("Wrong details. Check again");
                    vid.setText("");
                    dobText.setText("");
                }else{
                    voterDetails.user=user1;
                    candidateDetails.user=user1;
//                    String message= "Welcome "+Fname+" "+Lname+"!";
//                    JOptionPane.showMessageDialog(null,message);
                    voterDetails vd = new voterDetails();
                        vd.setVisible(true);
                        setVisible(false);
                }
                
                
                
                
            
                rs.close();
             
              
                
                   
    }
        catch (SQLException e) {
            System.err.println(e);
        }
        
        
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dobText;
    private javax.swing.JButton home;
    private javax.swing.JLabel invalidText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton submit;
    private javax.swing.JTextField vid;
    // End of variables declaration//GEN-END:variables
}
