/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import models.User;

/**
 *
 * @author Shazia
 */
public class voterDetails extends javax.swing.JFrame {
    static User user;
    /**
     * Creates new form voterDetails
     */
    public voterDetails() {
        initComponents();
         setSize(500,500);
        setTitle("Election Commision");
        
            nameText.setText(user.getFname()+" "+user.getLname());
        dobText.setText(user.getDob());
        vidText.setText(""+user.getVoterid());
        wardText.setText(""+user.getWardno());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        candButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        dobText = new javax.swing.JLabel();
        vidText = new javax.swing.JLabel();
        wardText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voter Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(161, 70, 190, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(177, 355, 61, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(203, 142, 35, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(161, 179, 77, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Voter ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(187, 216, 51, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ward");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(204, 253, 34, 17);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(59, 198, 0, 0);

        candButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        candButton.setText("Click");
        candButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candButtonActionPerformed(evt);
            }
        });
        getContentPane().add(candButton);
        candButton.setBounds(268, 290, 59, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("List of contesting candidates");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(65, 294, 173, 17);

        nameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameText.setText("Shazia Talib");
        getContentPane().add(nameText);
        nameText.setBounds(268, 142, 194, 17);

        dobText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dobText.setText("2001-06-10");
        getContentPane().add(dobText);
        dobText.setBounds(268, 179, 129, 17);

        vidText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vidText.setText("1011");
        getContentPane().add(vidText);
        vidText.setBounds(268, 216, 129, 17);

        wardText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wardText.setText("200");
        getContentPane().add(wardText);
        wardText.setBounds(268, 253, 101, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myPackage/background1.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       voterLogin vl = new voterLogin();
        vl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void candButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candButtonActionPerformed
        // TODO add your handling code here:
        candidateDetails cd1 = new candidateDetails();
        cd1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_candButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voterDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voterDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton candButton;
    private javax.swing.JLabel dobText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel vidText;
    private javax.swing.JLabel wardText;
    // End of variables declaration//GEN-END:variables
}
